name: Publish web components to NPM

on:
  release:
    types: [published]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/web-components
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.com/
          
      # (optional) ensure a fresh npm with latest trusted-publish bits
      - run: npm i -g npm@latest
      
      - run: npm ci
      
      - run: npm run publish
      
      - run: npm publish --access public
